name: Java CI with Maven - Build WAR on HelloServlet Change

on:
  push:
    branches: [ main, feature-hello ] #feature-hello, cho phép kiểm tra sớm
    #paths:
    #  - 'src/main/java/com/example/HelloServlet.java' # Chỉ chạy khi HelloServlet.java thay đổi
  pull_request:
      branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Verify with Maven
      run: mvn clean verify # Kiểm tra mã
    - name: Build with Maven
      run: mvn package # Build WAR
    - name: Upload WAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: servlet-war
        path: target/*.war
        if-no-files-found: error

