name: Java CI with Maven - Dịch và ghi WAR

on:
  push:
    branches: [ main, "feature-*" ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # Cập nhật phiên bản checkout
    - name: Set up JDK 17
      uses: actions/setup-java@v4 # Cập nhật phiên bản setup-java
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn clean package
    - name: Upload WAR artifact
      uses: actions/upload-artifact@v4 # Cập nhật lên v4
      with:
        name: servlet-war
        path: target/*.war
        if-no-files-found: error # Báo lỗi nếu không tìm thấy file WAR